# ==============================================================================
#
#  Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#  All rights reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# ==============================================================================
"""
This module extracts MoE components as subgraph in the graph
"""

from dataclasses import dataclass
from typing import Callable

import numpy as np
import onnx_ir as ir

from qairt.optimizer.onnx.graph import SubGraphDesc
from qairt.optimizer.onnx.passes.base import BasePredicatePass, MatchInfoProtocol
from qairt.optimizer.onnx.passes.cleaning import DeadCodeRemovalRewriter
from qairt.optimizer.onnx.utils.binop_binary_tree_utils import collect_connected_binelewise_ops
from qairt.optimizer.onnx.utils.utils import (
    OpTypePredicate,
    check_static_shape_of_node_io,
    get_constant_np,
    get_immediate_dominator_of_value,
    get_value_numeric_shape,
    is_constant,
    scan_lca_interleaved,
    scan_previous_nearest_candidate,
)
from qairt.optimizer.utils.logger import logger

MOE_FUNC_DOMAIN_NAME = "qairt.internal.block.MoE"

MOE_EXPERT_FUNC_NAME = "MoE_Expert"
MOE_EXPERT_FACTOR_FUNC_NAME = "MoE_ExpertFactor"
MOE_EXPERT_OP_PRED_FUNC_NAME = "MoE_ExpertPredCond"
MOE_ROUTER_FUNC_NAME = "MoE_Router"
MOE_AGGREGATION_FUNC_NAME = "MoE_Aggregation"
MOE_DYN_EXPERT_FUNC_NAME = "MoE_DynExpert"
MOE_DYN_OP_PRED_FUNC_NAME = "MoE_DynOpPred"


"""

* Definition for MoE_Router block (for one expert):
    - inputs:
        - router_in
    - outputs:
        - expert_factors (the multiplication factors for all experts)
        - activate_top_k_indices (the first topk output, for AR1 and ARN)
        - normalized_topk_factors (normalized factor generated by the last topk output, for AR1 and ARN)
        - op_pred_input (optional, for ARN only, usually produced by the second topk)

* Definition for MoE_ExpertPredCond block (for one expert):
    - inputs:
        - op_pred_input (usually produced by the second topk, shared by all MoE_ExpertPredCond blocks of same MoE layer)
    - outputs:
        - op_pred_condition (scalar)


* Definition for MoE_Expert block (for one expert):
    - inputs:
        - expert_inputs (shared by all MoE_Expert blocks of same MoE layer)
        - expert_factor (the multiplication factors for this experts, should be a tensor with only one element or scalar)
    - outputs:
        - weighted_output (tensor)
        - expert_outputs (tensor)

 *Definition for MoE_ExpertFactor block (for one expert):
    - inputs:
        - expert_factors (the multiplication factors for all experts, produced by ScatterElements, shared by all MoE_Expert blocks of same MoE layer)
    - outputs:
        - expert_factor (tensor)


* Definition for MoE_Aggregation block (with op predicate):
    - inputs:
        - expert_0_weighted_output (tensor)
        - expert_1_weighted_output (tensor)
        - expert_0_op_pred_condition (scalar)
        - expert_1_op_pred_condition (scalar)
        ...
    - attributes:
        - op_predicate = 1
    - outputs:
        - moe_final_output (tensor)


* Definition for MoE_Aggregation block (without op predicate):
    - inputs:
        - expert_0_weighted_output (tensor)
        - expert_1_weighted_output (tensor)
        ...
    - attributes:
        - op_predicate = 0
    - outputs:
        - moe_final_output (tensor)

For ARN graph, after running this Pass, a MoE layer will be transformed into

    expert_factors, activate_top_k_indices, activate_top_k_values, op_pred_input = MoE_Router(router_in)

    # for expert0
    expert_0_op_pred_condition = MoE_ExpertPredCond.expert0(op_pred_input)
    expert_0_factor = MoE_ExpertFactor.expert0(expert_factors)
    expert_0_weighted_output = MoE_Expert.expert0(expert_input, expert_0_factor)


    # for expert1
    expert_1_op_pred_condition = MoE_ExpertPredCond.expert1(op_pred_input)
    expert_1_factor = MoE_ExpertFactor.expert1(expert_factors)
    expert_1_weighted_output = MoE_Expert.expert1(expert_input, expert_1_factor)

    ....

    # aggregation
    moe_final_output = MoE_Aggregation(expert_0_weighted_output, expert_1_weighted_output, ...
                                       expert_0_op_pred_condition, expert_1_op_pred_condition, ...
                                        op_predicate=1
                                       )

For AR1 graph, after running this Pass, a MoE layer will be transformed into

    expert_factors, activate_top_k_indices, activate_top_k_values, op_pred_input = MoE_Router(router_in)

    # for expert0
    expert_0_factor = MoE_ExpertFactor.expert0(expert_factors)
    expert_0_weighted_output = MoE_Expert.expert0(expert_input, expert_0_factor)


    # for expert1
    expert_1_factor = MoE_ExpertFactor.expert1(expert_factors)
    expert_1_weighted_output = MoE_Expert.expert1(expert_input, expert_1_factor)

    ....

    # aggregation
    moe_final_output = MoE_Aggregation(expert_0_weighted_output, expert_1_weighted_output, ...
                                        op_predicate=0
                                       )
"""


class ExtractMoEComponents(BasePredicatePass):
    """
    Identify a MoE layer, and extract its subcomponents

    There are some rules we need to follow:
    - Identify should happens in match stage, do not modify any graph until we can confirm this is a MoE layer
    - in rewrite stage, we only need to wrap the nodes of each subcomponent into a subgraph

    """

    TRAVERSAL_ORDER = "bottom_up"
    MOE_AGGREGATION_FUNC_NAME = ""

    @dataclass
    class MatchInfo(MatchInfoProtocol):
        router_subgraph_desc: SubGraphDesc
        op_pred_cond_subgraph_desc_list: list[SubGraphDesc] | None
        expert_subgraph_desc_list: list[SubGraphDesc]
        factor_subgraph_desc_list: list[SubGraphDesc]
        agg_subgraph_desc: SubGraphDesc

    def _match_router_subgraph(
        self, expert_factors: ir.Value, op_pred_cond_subgraph_desc_list: list[SubGraphDesc] | None = None
    ):
        # assumption: router out is produced by a scatterelements (same for AR1 and ARN)
        bottom_scatter_elements_out = None
        for candidate_v in scan_previous_nearest_candidate(
            [expert_factors],
            check_fn=OpTypePredicate(["ScatterElements"]),
            ignore_fn=OpTypePredicate(["Reshape", "Transpose", "Squeeze", "Unsqueeze"]),
        ):
            bottom_scatter_elements_out = candidate_v
        if bottom_scatter_elements_out is None:
            return None
        router_in = get_immediate_dominator_of_value(bottom_scatter_elements_out, max_layer_to_traverse=20)
        if router_in is None:
            return None

        bottom_scatter_elements = bottom_scatter_elements_out.producer()
        normalized_topk_factors = bottom_scatter_elements.inputs[2]
        subgraph_outputs = [expert_factors]
        if op_pred_cond_subgraph_desc_list:
            # for ARN, we need to add op_pred_input as extra output to router subgraph
            subgraph_outputs += list(op_pred_cond_subgraph_desc_list[0].inputs)

        assert expert_factors.graph is not None  # check for mypy
        router_subgraph_desc = SubGraphDesc.infer_by_io(
            expert_factors.graph,
            inputs=[router_in],
            outputs=subgraph_outputs,
            max_layers_to_traverse=100,
        )

        # although the indices output of the first topk is not consumed by any external nodes,
        # we need to add it to the subgraph output (used in AdaptMoePass) to get the dynamic_expert_id
        activate_top_k_indices = None
        for n in router_subgraph_desc.nodes:
            if n.op_type == "TopK":
                activate_top_k_indices = n.outputs[1]
                break
        if activate_top_k_indices is None:
            return None

        # for ARN1, router block has 3 outputs:
        #     - expert_factors (the multiplication factors for all experts)
        #     - activate_top_k_indices (the first topk output, for AR1 and ARN)
        #     - normalized_topk_factors (the normalizedfactor generated from last topk output, for AR1 and ARN)
        # for ARN, router block has an additional output
        #     - op_pred_input (optional, for ARN only, usually produced by the second topk)

        subgraph_outputs = [expert_factors, activate_top_k_indices, normalized_topk_factors]
        if op_pred_cond_subgraph_desc_list:
            # for ARN, we need to add op_pred_input as extra output to router subgraph
            subgraph_outputs += list(op_pred_cond_subgraph_desc_list[0].inputs)
        router_subgraph_desc.outputs = subgraph_outputs

        return router_subgraph_desc

    def _determine_expert_out_and_factor(self, expert_weighted_v: ir.Value):
        """
        weighted_expert = Mul(expert_out_v, expert_factor)

        Since Mul inputs are interchangeable, to determin which one is factor,
        we assume expert_factor should be a succeed node of "Gather"
        """
        mul_out_v = None
        for candidate_v in scan_previous_nearest_candidate(
            [expert_weighted_v],
            check_fn=OpTypePredicate(["Mul"]),
            ignore_fn=OpTypePredicate(["Reshape", "Transpose", "Squeeze", "Unsqueeze"]),
        ):
            mul_out_v = candidate_v

        if mul_out_v is None:
            return None

        mul_node = mul_out_v.producer()
        if mul_node.op_type != "Mul":
            return None
        expert_factor_v = None
        gather_node = None
        expert_id = None
        for v in mul_node.inputs:
            for candidate_v in scan_previous_nearest_candidate(
                [v],
                check_fn=OpTypePredicate(["Gather"]),
                ignore_fn=OpTypePredicate(["Reshape", "Transpose", "Squeeze", "Unsqueeze"]),
            ):
                expert_factor_v = v
                gather_node = candidate_v.producer()
                expert_id = get_constant_np(gather_node.inputs[1])
                if expert_id.size != 1:
                    return None
                expert_id = int(expert_id.item())
                break

        if expert_factor_v is None or expert_id is None:
            return None
        expert_out_v = [x for x in mul_node.inputs if x is not expert_factor_v][0]

        return {
            "expert_out_v": expert_out_v,
            "expert_factor_v": expert_factor_v,
            "gather_node": gather_node,
            "expert_id": expert_id,
        }

    def _match_expert_blocks_and_factor_blocks(
        self, graph: ir.Graph, expert_weighted_outputs: list[ir.Value]
    ) -> tuple[list[SubGraphDesc], list[SubGraphDesc]] | None:
        expert_output_list = []
        expert_factor_list = []
        expert_id_list = []
        for weighted_output in expert_weighted_outputs:
            res = self._determine_expert_out_and_factor(weighted_output)
            if res is None:
                return None
            expert_output_list.append(res["expert_out_v"])
            expert_factor_list.append(res["expert_factor_v"])
            expert_id_list.append(res["expert_id"])

        # make sure all expert id exist
        expert_id_set = set(expert_id_list)
        for i in range(len(expert_id_list)):
            if i not in expert_id_set:
                logger.warning(f"expert id {i} does not exist, so skip this MoE layer")
                return None

        # the input of every expert
        expert_input = scan_lca_interleaved(expert_output_list, 100)
        if expert_input is None:
            return None

        # the multiplication factors for all experts, typically produced by ScatterElements op
        expert_factors = scan_lca_interleaved(expert_factor_list, 100)
        if expert_factors is None:
            return None

        expert_subgraph_desc_list = []
        # get expert subgraphs, and replace it by onnx ir function
        for expert_i in range(len(expert_output_list)):
            expert_subgraph_desc = SubGraphDesc.infer_by_io(
                graph,
                inputs=[expert_input, expert_factor_list[expert_i]],
                outputs=[expert_weighted_outputs[expert_i]],
                max_layers_to_traverse=100,
            )
            expert_subgraph_desc.meta["expert_id"] = expert_id_list[expert_i]
            expert_subgraph_desc_list.append(expert_subgraph_desc)

        factor_subgraph_desc_list = []
        for expert_i in range(len(expert_output_list)):
            factor_subgraph_desc = SubGraphDesc.infer_by_io(
                graph,
                inputs=[expert_factors],
                outputs=[expert_factor_list[expert_i]],
                max_layers_to_traverse=100,
            )
            factor_subgraph_desc.meta["expert_id"] = expert_id_list[expert_i]
            factor_subgraph_desc_list.append(factor_subgraph_desc)
        return expert_subgraph_desc_list, factor_subgraph_desc_list

    def match(self, graph, node):
        # match MoE components bottom-up
        # start by the aggregation block
        agg_subgraph_desc = self._match_aggregation_block(graph, node)
        if agg_subgraph_desc is None:
            return False
        expert_num = agg_subgraph_desc.meta["expert_num"]

        expert_weighted_outputs: list[ir.Value] = agg_subgraph_desc.inputs[:expert_num]

        # match all expert blocks
        res = self._match_expert_blocks_and_factor_blocks(graph, expert_weighted_outputs)
        if res is None:
            return False
        expert_subgraph_desc_list, factor_subgraph_desc_list = res

        op_pred_cond_subgraph_desc_list = None
        if agg_subgraph_desc.meta["op_predicate"]:
            # match all op_predication_condition blocks
            op_pred_conditions: list[ir.Value] = agg_subgraph_desc.inputs[expert_num:]

            op_pred_cond_subgraph_desc_list = self._match_op_pred_blocks(graph, op_pred_conditions)
            if op_pred_cond_subgraph_desc_list is None:
                return False
            for op_pred_subgraph_desc, expert_subgraph_desc in zip(
                op_pred_cond_subgraph_desc_list, expert_subgraph_desc_list
            ):
                op_pred_subgraph_desc.meta["expert_id"] = expert_subgraph_desc.meta["expert_id"]

        # match the router block
        expert_factors = factor_subgraph_desc_list[0].inputs[0]
        router_subgraph_desc = self._match_router_subgraph(expert_factors, op_pred_cond_subgraph_desc_list)
        if router_subgraph_desc is None:
            return False

        return self.MatchInfo(
            router_subgraph_desc=router_subgraph_desc,
            expert_subgraph_desc_list=expert_subgraph_desc_list,
            factor_subgraph_desc_list=factor_subgraph_desc_list,
            op_pred_cond_subgraph_desc_list=op_pred_cond_subgraph_desc_list,
            agg_subgraph_desc=agg_subgraph_desc,
        )

    def rewrite(self, graph: ir.Graph, node: ir.Node, match_info: MatchInfoProtocol | None = None) -> bool:
        assert isinstance(match_info, self.MatchInfo)

        if len(match_info.expert_subgraph_desc_list) < 2:
            # we need to run lca algorithm, so at least we need 2 experts
            return False

        # To present the extracted components directly into the graph,
        # each component subgraph will be wrapped to a ir.Function
        # and one caller node will be inserted to call this function

        model_ir = match_info.extra_info.model_ir  # we need model_ir to add function into ir

        # replace subgraph by function
        # note: this replacement will change the output value of subgraph by the function caller's output,
        #       and this changement will not affect the inputs recorded by other SubgraphDesc,
        #       so we must do the replacement in bottom-up order

        agg_block_call_node = match_info.agg_subgraph_desc.replace_as_function(
            model_ir,
            MOE_AGGREGATION_FUNC_NAME,
            domain=MOE_FUNC_DOMAIN_NAME,
            opset_version=1,
            attributes=[
                ir.AttrInt64("op_predicate", match_info.agg_subgraph_desc.meta["op_predicate"]),
                ir.AttrInt64("expert_num", match_info.agg_subgraph_desc.meta["expert_num"]),
            ],
        )

        if match_info.op_pred_cond_subgraph_desc_list:
            for subgraph_desc in match_info.op_pred_cond_subgraph_desc_list:
                op_pred_cond_block_call_node = subgraph_desc.replace_as_function(
                    model_ir,
                    MOE_EXPERT_OP_PRED_FUNC_NAME,
                    domain=MOE_FUNC_DOMAIN_NAME,
                    opset_version=1,
                    attributes=[ir.AttrInt64("expert_id", subgraph_desc.meta["expert_id"])],
                )

        for subgraph_desc in match_info.expert_subgraph_desc_list:
            expert_block_call_node = subgraph_desc.replace_as_function(
                model_ir,
                MOE_EXPERT_FUNC_NAME,
                domain=MOE_FUNC_DOMAIN_NAME,
                opset_version=1,
                attributes=[ir.AttrInt64("expert_id", subgraph_desc.meta["expert_id"])],
            )

        for subgraph_desc in match_info.factor_subgraph_desc_list:
            expert_factor_call_node = subgraph_desc.replace_as_function(
                model_ir,
                MOE_EXPERT_FACTOR_FUNC_NAME,
                domain=MOE_FUNC_DOMAIN_NAME,
                opset_version=1,
                attributes=[ir.AttrInt64("expert_id", subgraph_desc.meta["expert_id"])],
            )

        router_call_node = match_info.router_subgraph_desc.replace_as_function(
            model_ir,
            MOE_ROUTER_FUNC_NAME,
            domain=MOE_FUNC_DOMAIN_NAME,
            opset_version=1,
        )

        return True

    def post_each_rewrite_hook(self, ctx, rewrite_success):
        if rewrite_success:
            # we need to clean the MoE nodes after we have extracted them into functions
            # otherwise, _match_aggregation_block will match many times for the same MoE layer
            DeadCodeRemovalRewriter().apply(ctx)

    def _match_op_pred_blocks(
        self, graph, expert_pred_conditions: list[ir.Value]
    ) -> list[SubGraphDesc] | None:
        cond_input = scan_lca_interleaved(expert_pred_conditions, 100, lambda x: not is_constant(x))
        if cond_input is None:
            return None

        op_pred_cond_subgraph_desc_list: list[SubGraphDesc] = []

        for pred_cond in expert_pred_conditions:
            cond_subgraph_desc = SubGraphDesc.infer_by_io(
                graph,
                inputs=[cond_input],
                outputs=[pred_cond],
                max_layers_to_traverse=100,
            )
            op_pred_cond_subgraph_desc_list.append(cond_subgraph_desc)
        return op_pred_cond_subgraph_desc_list

    def _match_aggregation_block(self, graph: ir.Graph, node: ir.Node) -> SubGraphDesc | None:
        subgraph_desc = _match_aggregation_block_with_op_pred(graph, node)
        if subgraph_desc is not None:
            return subgraph_desc

        subgraph_desc = _match_aggregation_block_without_op_pred(graph, node)
        if subgraph_desc is not None:
            return subgraph_desc

        return None


def _match_aggregation_block_with_op_pred(graph: ir.Graph, node: ir.Node) -> SubGraphDesc | None:
    """
    Bottom-up scan the subgraph
    {
        a_0 = Where(cond_0, x_0, 0)
        a_1 = Where(cond_1, a_0, Add(a_0, x_1))
        ...
        a_{n-1} = Where(cond_{n-1}, a_{n-1}, Add(a_{n-2}, x_{n-1}))
    }

    the x_i is the output of i-th expert
    """

    def _match_aggregation_block_subpattern(graph, node: ir.Node):
        """
        Bottom-up scan the subgraph, (the node is the where node)

        Subgraph(weighted_expert, expert_cond, chain_in_v) --> chain_out_v
        {
            res = Add(chain_in_v, weighted_expert) # inputs can be interchanged
            chain_out_v = Where(expert_cond, res, chain_in_v)
        }

        Since Mul inputs are interchangeable, to determin which one is factor,
        we assume expert_factor should be a succeed node of "ScatterElement"
        """
        if node is None or node.op_type != "Where":
            return None
        where_node = node
        add_out = node.inputs[1]
        assert add_out is not None  # check for mypy
        add_node = add_out.producer()
        if add_node is None or add_node.op_type != "Add":
            return None
        chain_in_v = where_node.inputs[2]
        if chain_in_v not in add_node.inputs:
            return None
        expert_weighted_v = [x for x in add_node.inputs if x is not where_node.inputs[2]][0]

        return {
            "chain_in_v": where_node.inputs[2],
            "chain_out_v": where_node.outputs[0],
            "expert_cond": where_node.inputs[0],
            "expert_weighted_v": expert_weighted_v,
        }

    if node.op_type != "Where":
        return None  # quick return

    subchain_info_reverse_list = []
    curr_where_node = node
    while True:
        subchain_info = _match_aggregation_block_subpattern(graph, curr_where_node)
        if subchain_info is None:
            break
        subchain_info_reverse_list.append(subchain_info)
        curr_where_node = subchain_info["chain_in_v"].producer()

    if len(subchain_info_reverse_list) == 0:
        return None
    # reverse it to top-down order
    subchain_info_list = list(reversed(subchain_info_reverse_list))
    expert_weighted_outputs: list[ir.Value] = []
    expert_pred_conditions: list[ir.Value] = []

    # note: for N chained Where op, there are only N-1 subchain_info
    # the top Where is special
    top_where = subchain_info_list[0]["chain_in_v"].producer()
    if top_where is None or top_where.op_type != "Where":
        return None
    top_where_y_np = get_constant_np(top_where.inputs[2])
    if top_where_y_np is None or (not (top_where_y_np == 0.0).all()):
        return None

    # top_where_x may be produced by an optional Add
    # Add(expert_weighted_out, zero_constant)
    expert_weighted_out = top_where.inputs[1]
    optional_add_op = expert_weighted_out.producer()
    if optional_add_op is not None and optional_add_op.op_type == "Add":
        real_expert_weighted_out_candidate = None
        for i, j in [(1, 0), (0, 1)]:
            if (
                is_constant(optional_add_op.inputs[i])
                and (get_constant_np(optional_add_op.inputs[i]) == 0).all()
            ):
                real_expert_weighted_out_candidate = optional_add_op.inputs[j]
                break
        if real_expert_weighted_out_candidate is not None:
            # broadcast is not allowed
            check_static_shape_of_node_io(optional_add_op)
            if get_value_numeric_shape(optional_add_op.outputs[0]) == get_value_numeric_shape(
                real_expert_weighted_out_candidate
            ):
                expert_weighted_out = real_expert_weighted_out_candidate

    expert_weighted_outputs.append(expert_weighted_out)
    expert_pred_conditions.append(top_where.inputs[0])

    # for the rest Where, we can use the same logic
    for subchain in subchain_info_list:
        expert_weighted_outputs.append(subchain["expert_weighted_v"])
        expert_pred_conditions.append(subchain["expert_cond"])

    agg_block_inputs = [*expert_weighted_outputs, *expert_pred_conditions]

    moe_final_output = subchain_info_list[-1]["chain_out_v"]
    subgraph_desc = SubGraphDesc.infer_by_io(
        graph,
        inputs=agg_block_inputs,
        outputs=[moe_final_output],
        max_layers_to_traverse=200,  # need a large value for 128 experts
    )
    subgraph_desc.meta["op_predicate"] = 1
    subgraph_desc.meta["expert_num"] = len(expert_weighted_outputs)
    return subgraph_desc


def _match_aggregation_block_without_op_pred(graph: ir.Graph, node: ir.Node) -> SubGraphDesc | None:
    """
    Bottom-up scan the subgraph
    {
        a_n = AddSubgraph(x_0, x_1, ..., x_{n-1})

        # AddSubgraph is formed by Add and Identity (optional)
        # they can be serial or tree-like
    }

    the x_i is the output of i-th expert
    """
    if node.op_type != "Add":
        return None

    # we are matching the node bottom-up
    # so the last node of the connected-Add-ops will be matched firstly
    leave_values, connected_nodes, max_height = collect_connected_binelewise_ops(
        node, require_same_encodings=False, skip_op_types=["Identity"]
    )

    expert_weighted_outputs: list[ir.Value] = []
    moe_final_output = node.outputs[0]

    # leave values are:
    #  - expert_weighted_v
    #  - 0 tensor (sometimes, there will be Add(0, x_0))

    # filter out 0-tensor
    for v in leave_values:
        if is_constant(v):
            if not (get_constant_np(v) == 0).all():
                return None
        else:
            expert_weighted_outputs.append(v)

    # Validate minimum number of experts (MoE requires at least 2 experts)
    if len(expert_weighted_outputs) < 2:
        return None

    subgraph = SubGraphDesc.infer_by_io(
        graph,
        inputs=expert_weighted_outputs,  # not sorted by expert id, because we currently don't know their expert id
        outputs=[moe_final_output],
        max_layers_to_traverse=(
            max_height * 3
        ),  # there maybe Identity in the graph, so set the budget large enough.
    )
    subgraph.meta["op_predicate"] = 0
    subgraph.meta["expert_num"] = len(expert_weighted_outputs)
    return subgraph
