@startuml

autonumber "<b>[#]"

participant "PD1 - C1 [low]"   as cv #royalblue
participant "PD1 - QNN [low]"  as qnn1 #green
participant "PD2 [high]"  as pd2 #red
participant "HAP"  as hap 

qnn1 -[#green]> hap: acquire(6,8)
cv -[#blue]> hap: acquire(2,1)

pd2 -[#red]> hap: acquire(6,8)
activate hap
hap --[#black]> cv: release_request
hap --[#black]> qnn1: release_request
cv -[#blue]> hap: release()
qnn1 -[#green]> hap: release()
hap --[#black]> pd2: ok
deactivate hap

cv -[#blue]> hap: acquire(1,2)
activate hap
qnn1 -[#green]> hap: acquire(6,8)
pd2 -[#red]> hap: release()
hap --[#black]> cv: ok
hap --[#black]> qnn1: ok
deactivate hap

@enduml

