# ==============================================================================
#
#  Copyright (c) Qualcomm Technologies, Inc.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# ==============================================================================
""" Fie contains code for helper utility functions used by MAD library """
import json
import re
import os
import logging
from string import Template
from types import SimpleNamespace
from typing import Dict

import msgpack, zstandard as zstd, pathlib as pl

from qti.aisw.converters.common.converter_ir.op_graph_optimizations import IROptimizations
from qti.aisw.converters.common import ir_graph as ir_graph_lib
from qti.aisw.converters.common import ir_quantizer

from qti.aisw.converters.common import modeltools

logger = logging.getLogger(__name__)


ir_graph_utils_helper = ir_graph_lib.PyIrGraph('utils')
ZSTD_COMPRESSION_LEVEL = 3

def get_ir_graph(dlc_path):
    """
    Loads an IR graph from a DLC file.

    :param dlc_path[str]: The path to the DLC file.
    :return: A tuple containing the IR graph and the IrDlcReader object.
    """
    dlc_reader = modeltools.IrDlcReader(
        dlc_path,
        disableLazyWeightLoading=True
    )
    graph = dlc_reader.get_ir_graph()
    return graph, dlc_reader

def save_ir_graph_to_dlc(ir_graph, save_path):
    """
    Saves an IR graph to a DLC file.

    :param ir_graph: The IR graph to save.
    :param save_path[str]: The path to save the DLC file.
    """
    meta_string = "Generated by MAD v0"

    dlc_serializer = modeltools.IrDlcSerializer(save_path, meta_string, converterCommandlineString='N.A.')
    dlc_serializer.initialize()
    dlc_serializer.serialize(ir_graph)
    if dlc_serializer.finish():
        logger.info(f"DLC file is saved successfully: {save_path}")
    else:
        logger.error(f"DLC file is not saved :( {save_path}")


def quantize_graph(ir_graph):
    """
    Quantizes the given IR graph.

    :param ir_graph: The IR graph to quantize.
    """
    # Set Quantizer option
    quant_opts = ir_quantizer.IrQuantizerOpts()
    quant_opts.keep_weights_quantized = True
    quant_opts.use_fallback_to_float = True
    quant_opts.float_bw = 16
    quant_opts.float_bias_bw = 16
    quant_opts.use_dynamic_16_bit_weights = True
    quantizer = ir_quantizer.IrQuantizer(quant_opts, ir_graph)
    quantizer.quantize()


def set_encoding_for_tensor(ir_tensor: ir_graph_lib.IrTensor, quant_info: ir_graph_lib.IrQuantizationInfo):
    """
    Sets encoding for a tensor in the same way QNN does.

    :param ir_tensor[ir_graph_lib.IrTensor]: IR tensor for which the encoding must be set.
    :param quant_info[ir_graph_lib.IrQuantizationInfo]: Quantization information to be set for the given IR tensor.
    :raises AssertionError: If `quant_info` is undefined for a quantizable tensor.
    """
    if quant_info.type != ir_graph_lib.Qnn_QuantizationEncoding_t.QNN_QUANTIZATION_ENCODING_UNDEFINED and ir_tensor.is_quantizable():
        ir_tensor.set_encoding(ir_tensor.data_type(), quant_info)
        return

    if quant_info.type == ir_graph_lib.Qnn_QuantizationEncoding_t.QNN_QUANTIZATION_ENCODING_UNDEFINED:
        err_str = (f'QuantInfo not defined for quantizable tensor, {ir_tensor.name()}. Must set valid '
                   f'quantization info w/quantized data types')
        raise AssertionError(err_str)

def apply_encoding(ir_graph, encoding_file):
    """
    Applies quantization encodings from a JSON file to the IR graph.

    :param ir_graph: The IR graph to apply encodings to.
    :param encoding_file: Path to the JSON file containing encoding information.
    """
    encodings = load_encodings(encoding_file)

    param_encodings = encodings['param_encodings']
    activation_encodings = []
    if 'activation_encodings' in encodings:
        activation_encodings = encodings['activation_encodings']


    for encoding in param_encodings + activation_encodings:
        tensor_name = encoding['name']
        if ir_graph.has_tensor(tensor_name):
            logger.debug(f"Applying encoding for tensor: {tensor_name}")
            ir_tensor = ir_graph.get_tensor(tensor_name)
            aimet_encoding = IROptimizations.extract_encoding_dict(tensor_name, [encoding], version="1.0.0")
            if 'dtype' in aimet_encoding:
                aimet_encoding.pop('dtype')
            quant_info = ir_graph_utils_helper.fill_quant_info(aimet_encoding)
            set_encoding_for_tensor(ir_tensor, quant_info)


def load_encodings(encoding_file_path) -> Dict:
    buf = (pl.Path(encoding_file_path)).read_bytes()
    dctx = zstd.ZstdDecompressor()
    raw = dctx.decompress(buf)
    return msgpack.unpackb(raw, raw=False)

def save_encodings(data: Dict, encoding_file_path: str):
    raw = msgpack.packb(data, use_bin_type=True)
    cctx = zstd.ZstdCompressor(level=ZSTD_COMPRESSION_LEVEL)
    (pl.Path(encoding_file_path)).write_bytes(cctx.compress(raw))


def update_io_names(ir_graph):
    """
    Updates the input/output tensor names of an IR graph generated by MAD

    This method updates the input/output tensor of a graph generated by MAD to comply with
    the naming requirements of Qualla/Genie Tools. This is a sample method built for
    LLaMa model and is mostly reusable.
    Note: Tensors are updated in-place.

    :param ir_graph: IrGraph with input/output names as per the MAD convention.
    """
    graph_inputs = ir_graph.get_input_tensors_to_graph()
    graph_outputs = ir_graph.get_output_tensors_of_graph()
    input_maps = {
        '.input_ids': Template('input_ids'),
        '.attention_mask': Template('attention_mask'),
        '.position_ids_sin': Template('position_ids_sin'),
        '.position_ids_cos': Template('position_ids_cos'),
        '.past_key_in': Template('past_key_${num}_in'),
        '.past_value_in': Template('past_value_${num}_in'),
    }

    output_maps = {
        '.logits' : Template('logits'),
        '.past_key_out': Template('past_key_${num}_out'),
        '.past_value_out': Template('past_value_${num}_out'),
    }
    updated_input_names = []
    updated_output_names = []
    for tensor in graph_inputs:
        # tensor = ir_graph.get_tensor(tensor_name)
        tensor_name = tensor.name()
        for key, template in input_maps.items():
            if key in tensor_name:
                placeholders = re.findall(r"\$\{(\w+)\}", template.template)
                if len(placeholders) == 0:
                    updated_name = template.safe_substitute()
                else:
                    # Extract the decoder blocks number from the original tensor name.
                    # As per the naming convention used in MAD .. it will be on 2nd index pf the tensor name split.
                    # e.g 'model.past_key_in.0'  on split using '.' 0 which is the block no will be in 2nd position.
                    block_no = tensor_name.split('.')[2]
                    updated_name = template.safe_substitute({placeholders[0]: block_no})

                # tensor.set_name(updated_name)
                # ir_graph.add_tensor(tensor)
                ir_graph.update_tensor_name(tensor_name, updated_name)
                logger.debug(f"Tensor name updated: {tensor_name} ==> {updated_name}")
                updated_input_names.append(updated_name)
                break

    for tensor in graph_outputs:
        # tensor = ir_graph.get_tensor(tensor_name)
        tensor_name = tensor.name()
        for key, template in output_maps.items():
            if key in tensor_name:
                placeholders = re.findall(r"\$\{(\w+)\}", template.template)
                if len(placeholders) == 0:
                    updated_name = template.safe_substitute()
                else:
                    # Extract the decoder blocks number from the original tensor name.
                    # As per the naming convention used in MAD .. it will be on 2nd index pf the tensor name split.
                    # e.g 'model.decoder_blocks.0.past_key_out_output_0' on split using '.' 0 which is the block no will be in 2nd position.
                    block_no = tensor_name.split('.')[2]
                    updated_name = template.safe_substitute({placeholders[0]: block_no})

                # tensor.set_name(updated_name)
                # ir_graph.add_tensor(tensor)
                ir_graph.update_tensor_name(tensor_name, updated_name)
                logger.debug(f"Tensor name updated: {tensor_name} ==> {updated_name}")
                updated_output_names.append(updated_name)
                break
    return updated_input_names, updated_output_names


def split_and_serialize(ir_graph, graph_split, save_dir = './', file_prefix = 'model'):
    """
    Splits an IR graph into multiple sub-graphs based on specified split points
    and serializes each sub-graph into a DLC file.

    :param ir_graph: The original IR graph to split.
    :param graph_split[list]: List of tensor names at which to split the graph.
    :param save_dir[str, optional]: Directory to save the split DLC files. Defaults to './'.
    :param file_prefix[str, optional]: Prefix for the names of the saved DLC files. Defaults to 'model'.
    :raises ValueError: If a specified split tensor is not found in the graph.
    """
    # Validate split points exist in the graph
    for split_tensor in graph_split:
        if not ir_graph.has_tensor(split_tensor):
            raise ValueError(f"Split tensor '{split_tensor}' not found in graph")

    num_splits = len(graph_split) + 1

    # Get the names of input tensors of the graph
    graph_inputs = [tensor.name() for tensor in ir_graph.get_input_tensors_to_graph()]

    graphs = []
    for i in range(num_splits):
        graph_name = ir_graph.name + f"_{i+1}_of_{num_splits}"
        graphs.append(
            ir_graph_lib.IrGraph(
                name= graph_name
            )
        )

    cnt = 0
    for op in ir_graph.get_ops():
        # Add all the input of the op to the graph
        #   1. If a tensor_name is in graph input or the graph_split node mark it as model input
        #   2. If a tensor is static tensor add the data as well.
        for tensor in op.inputs():
            tensor_name = tensor.name()
            if tensor_name in graph_inputs + graph_split:
                tensor.set_tensor_type(ir_graph_lib.IR_TENSOR_TYPE_APP_WRITE)
            if not graphs[cnt].has_tensor(tensor_name):
                graphs[cnt].add_tensor(tensor)

        # Add all the output of the op to the graph
        #   1. If a tensor_name is in graph_split node mark it as model output

        split_graph = False
        for tensor in op.outputs():
            tensor_name = tensor.name()
            if tensor_name in graph_split:
                tensor.set_tensor_type(ir_graph_lib.IR_TENSOR_TYPE_APP_READ)
                split_graph = True
                logger.info(f"First split processed at `{tensor_name}` after Op: {op.name}")

            graphs[cnt].add_tensor(tensor)

        # Add op
        graphs[cnt].add_op(op)

        if split_graph:
            save_path = os.path.join(save_dir, file_prefix + f'_{cnt+1}_of_{num_splits}.dlc')
            logger.info(f"Saving split {cnt}: {save_path}")
            save_ir_graph_to_dlc(graphs[cnt], save_path)
            cnt += 1

    # serialize the last part
    save_path = os.path.join(save_dir, file_prefix + f'_{cnt+1}_of_{num_splits}.dlc')
    logger.info(f"Saving split {cnt}: {save_path}")
    save_ir_graph_to_dlc(graphs[cnt], save_path)


def namespace_to_dict(obj):
    """
    Recursively convert SimpleNamespace objects to dictionaries
    """
    if isinstance(obj, SimpleNamespace):
        return {k: namespace_to_dict(v) for k, v in vars(obj).items()}
    elif isinstance(obj, dict):
        return {k: namespace_to_dict(v) for k, v in obj.items()}
    elif isinstance(obj, (list, tuple)):
        return type(obj)(namespace_to_dict(item) for item in obj)
    return obj
