#=============================================================================
#
#  Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#  All Rights Reserved.
#  Confidential and Proprietary - Qualcomm Technologies, Inc.
#
#=============================================================================

SOURCES := main.cpp

GENIE_C_API_HEADERS_INCLUDE := $(QNN_SDK_ROOT)/include/Genie

QNN_TARGET ?= aarch64-qnx800
export TARGET_DIR := ./bin/$(QNN_TARGET)

genie-t2t-run := $(TARGET_DIR)/genie-t2t-run

all: $(genie-t2t-run)

# Include paths
INCLUDES += -I$(GENIE_C_API_HEADERS_INCLUDE)

# set compiler flags
COMMON_CXXFLAGS = -std=c++20 -fPIC -Wall -pg -pthread $(INCLUDES) -Wl,-lc++ -D_GNU_SOURCE -D_QNX_SOURCE -Wl,-lm
COMMON_LDFLAGS = -L$(QNN_SDK_ROOT)/lib/$(QNN_TARGET) -lGenie

#TODO configure for these feature flags
CXXFLAGS += $(COMMON_CXXFLAGS) -Wno-write-strings -fvisibility=hidden
LDFLAGS += $(COMMON_LDFLAGS) -fvisibility=hidden -flto


OBJ_DIR_MAIN := obj/$(QNN_TARGET)

# Rule to make shared lib
.PHONY: genie-t2t-run
genie-t2t-run: $(genie-t2t-run)

# Compile rules
$(OBJ_DIR_MAIN)/%.o: main.cpp
	$(CXX) $(CXXFLAGS) -c $^ -o $@

# set up resources
directories := $(TARGET_DIR) $(OBJ_DIR_MAIN)

$(genie-t2t-run): $(OBJ_DIR_MAIN)/main.o | $(directories)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)


$(OBJ_DIR_MAIN)/main.o: | $(OBJ_DIR_MAIN)

# rule to create directories
$(directories):
	mkdir -p $@

.PHONY: clean
clean:
	rm -rf obj $(TARGET_DIR)
